miscellaneous: [
    { title: "The Secrets of Space Exploration", views: "3.2M", rating: 4.9, thumbnail: "https://via.placeholder.com/300x200?text=Space+Exploration" },
    { title: "Top 10 Life Hacks", views: "2.1M", rating: 4.7, thumbnail: "https://via.placeholder.com/300x200?text=Life+Hacks" },
    { title: "History of Ancient Civilizations", views: "1.8M", rating: 4.6, thumbnail: "https://via.placeholder.com/300x200?text=Ancient+History" },
    { title: "The Art of Cooking", views: "2.5M", rating: 4.8, thumbnail: "https://via.placeholder.com/300x200?text=Cooking+Art" },
    { title: "Top 5 Fitness Routines", views: "1.9M", rating: 4.5, thumbnail: "https://via.placeholder.com/300x200?text=Fitness+Routines" },
    { title: "Exploring the Deep Sea", views: "3.1M", rating: 4.9, thumbnail: "https://via.placeholder.com/300x200?text=Deep+Sea" },
    { title: "DIY Home Decor Ideas", views: "2.3M", rating: 4.6, thumbnail: "https://via.placeholder.com/300x200?text=DIY+Home+Decor" },
    { title: "The Science Behind Climate Change", views: "2.8M", rating: 4.7, thumbnail: "https://via.placeholder.com/300x200?text=Climate+Science" },
    { title: "Top 10 Video Games of All Time", views: "3.0M", rating: 4.8, thumbnail: "https://via.placeholder.com/300x200?text=Top+Video+Games" },
    { title: "The Magic of Photography", views: "1.7M", rating: 4.5, thumbnail: "https://via.placeholder.com/300x200?text=Photography+Magic" },
    { title: "The World of Cryptocurrency", views: "2.4M", rating: 4.6, thumbnail: "https://via.placeholder.com/300x200?text=Cryptocurrency" },
    { title: "Top 10 Travel Destinations", views: "3.5M", rating: 4.9, thumbnail: "https://via.placeholder.com/300x200?text=Travel+Destinations" },
    { title: "Understanding Artificial Intelligence", views: "2.2M", rating: 4.7, thumbnail: "https://via.placeholder.com/300x200?text=AI+Understanding" },
    { title: "The Evolution of Music", views: "2.6M", rating: 4.8, thumbnail: "https://via.placeholder.com/300x200?text=Music+Evolution" },
    { title: "Tips for Better Gardening", views: "1.5M", rating: 4.4, thumbnail: "https://via.placeholder.com/300x200?text=Gardening+Tips" },
],